name: some_lessons_from_youtube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  retrofit: ^3.0.0
  logger: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^3.0.0
  build_runner: ^2.1.5



flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
  assets:
    - assets/